document.write('<div id="footer"> ');
document.write(' <div class="container"> ');
document.write('  <div class="row"> ');
document.write('   <div class="footer-links"> ');
document.write('    <a href="javascript:void(0)" onclick="SetHome(this,window.location)">设为首页</a>| ');
document.write('    <a href="javascript:void(0)" onclick="shoucang(document.title,window.location)">加入收藏</a>| ');
document.write('    <a href="http://jyj.czs.gov.cn/wzbz/default.htm" target="_blank">网站帮助</a>| ');
document.write('    <a href="http://jyj.czs.gov.cn/19935/index.htm" target="_blank">站点地图</a>| ');
document.write('    <a href="http://jyj.czs.gov.cn/lxwm/content_744619.html" target="_blank">联系我们</a> ');
document.write('   </div> ');
document.write('  </div> ');
document.write('  <div class="row"> ');
document.write('   <div class="col-md-3 footer-logo text-right"> ');
document.write('    <script type="text/javascript">document.write(unescape("%3Cspan id=\'_ideConac\' %3E%3C/span%3E%3Cscript src=\'http://dcs.conac.cn/js/19/283/0000/40519792/CA192830000405197920001.js\' type=\'text/javascript\'%3E%3C/script%3E"));</script> ');
document.write('   </div> ');
document.write('   <div class="col-md-6 text-center"> ');
document.write('    <h4> <p><span>主办单位：郴州市教育局</span><span>承办单位：郴州市政务服务中心</span></p> <p><span>备案/许可证编号：<a href="http://beian.miit.gov.cn" style="color:5D93C5" target="_blank">湘ICP备17014372号-4</a></span><span>网站标识码：4310000017 <script src="http://s19.cnzz.com/stat.php?id=4296251&web_id=4296251&show=pic" language="JavaScript"></script></span></p> <p><span><a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=43100302000177"><img src="http://jyj.czs.gov.cn/2018new/img/ba.png" border="0" /> 湘公网安备 43100302000177号</a></span><span>联系电话：0735-2884485</span><br /><span>邮箱地址：czjybgs@163.com</span></p> 　 </h4> ');
document.write('   </div> ');
document.write('   <div class="col-md-3 footer-logo text-left"> ');
document.write('    <span id="_span_jiucuo"></span>');
document.write('    <script id="_jiucuo_" sitecode="4310000017" src="https://zfwzgl.www.gov.cn/exposure/jiucuo.js"></script> ');
document.write('    <!--');
document.write('                        <a href="http://www.hunan.gov.cn/fzlm/wap/" target="_blank"><img src="/cms/siteResource/site252/_template/2018new/img/sapp.png" width="114" height="59"  border="0" /></a>--> ');
document.write('   </div> ');
document.write('  </div> ');
document.write(' </div> ');
document.write('</div> ');
document.write('<!--footer-->');
